# This is a basic workflow to help you get started with Actions

name: demo-kotlin-cicd-workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  #  paths-ignore:
  #    - '.github/**'
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Azure login
        uses: azure/login@v1.4.3
        with: # Set Azure credentials secret as an input
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: RUN az Command
        run : |
           az account show
           az group list 
     
      - name: check java version
        if: always()
        run: java -version
    # running gradle build 
      - name: gradle build
        run: gradle build
      
      - name: change permissions of gradlew
        run: chmod +x gradlew
      - name: gradlew build
        run: ./gradlew build
      - name: docker version
        run: |
            docker -v
            docker build . -t danikr238/demo-kotlin2.0
            docker images -a
      - name: docker login
        run: | 
         docker login -u ${{ secrets.dockerhubusername }} -p ${{ secrets.dockerhubpassword }}
         docker push danikr238/demo-kotlin2.0

      
